# Generated by Django 2.1.3 on 2018-11-26 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('boardid', models.AutoField(primary_key=True, serialize=False)),
                ('boardname', models.CharField(max_length=96)),
                ('boardr', models.IntegerField(default=0)),
                ('boardg', models.IntegerField(default=0)),
                ('boardb', models.IntegerField(default=0)),
                ('boardtiltx', models.IntegerField(default=0)),
                ('boardtilty', models.IntegerField(default=0)),
                ('boardbackgroundr', models.IntegerField(default=0)),
                ('boardbackgroundg', models.IntegerField(default=0)),
                ('boardbackgroundb', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
