# Generated by Django 2.1.3 on 2018-11-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20181128_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stims',
            name='stimshape',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
